name: CI (OSS)

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  test:
    if: github.event.pull_request.head.repo.full_name != github.repository
    uses: ./.github/workflows/test.yml
    with:
      saas: false
